feat(PL-2460): add write-only mode
nestoca/joy pull request #109
Opened 2024-03-05 18:39 UTC by j-martin

A better name is more than welcome. We joked around calling it `moist-run`. I need this change for my bulk `!lock`ing. So there it is.

2024-03-05 19:34 UTC, silphid requested changes
Great feature, though I find the name more confusing than anything (because of the likeliness to unrelated concepts of Read-Only, Read/Write, Write-Only).  It gives no clue as to what it really does.  Possible suggestions would be `--local`, `--local-only`, `--skip-pr`. What do you all think @nestoca/stream-platform?

2024-03-05 20:54 UTC, davidmdm reviewed
Whats' the difference with `--dry-run`? Is it just an alias?

I don't see any custom behavior that differentiates write-only from dry-run?

2024-03-05 21:11 UTC, silphid commented
> Whats' the difference with `--dry-run`? Is it just an alias?
> I don't see any custom behavior that differentiates write-only from dry-run?

Haha @davidmdm good catch, I didn't even realize it was doing same as dry-run! I guess it's @j-martin testing our review skills (and I just flunked! 😬)

2024-03-05 22:58 UTC, j-martin commented
When using `--dry-run` it actively does not write to disk:

https://github.com/nestoca/joy/blob/9cb9895f48bb03341c282a7a899da0d54cd9eb88/internal/release/promote/perform.go#L109-L115

To be fair it took me a few minutes to re-find it. At first, I thought you were right, about the code doing nothing more than `--dry-run`

2024-03-05 23:20 UTC, davidmdm commented
Weird I don't see what you posted in the changes...

2024-03-05 23:21 UTC, davidmdm approved these changes

2024-03-05 23:58 UTC, j-martin commented
@silphid I have renamed it to `--local-only`.

2024-03-06 00:12 UTC, silphid commented on cmd/joy/release.go
> +				return fmt.Errorf("flag --skip-catalog-update requires --dry-run or --write-only")
```suggestion
				return fmt.Errorf("flag --skip-catalog-update requires --dry-run or --local-only")
```

2024-03-06 00:15 UTC, silphid approved these changes
LGTM, only a few forgotten renames...

> To be fair it took me a few minutes to re-find it. At first, I thought you were right, about the code doing nothing more than --dry-run

Wow, yeah, that was subtle and indirect, but you're right! 👍

2024-03-06 00:15 UTC, silphid commented on internal/release/promote/perform.go
> +		modeName = "Write-Only"
```suggestion
		modeName = "Local-Only"
```

2024-03-06 00:15 UTC, silphid commented on internal/release/promote/promotion.go
> +		fmt.Println("ℹ️ Write-only mode enabled: The local repo will be modified, but not committed. No pull request will be created.")
```suggestion
		fmt.Println("ℹ️ Local-only mode enabled: The local repo will be modified, but not committed. No pull request will be created.")
```

2024-03-06 00:19 UTC, merged