chore(depot): build with depot
nestoca/joy pull request #205
Opened 2024-11-12 21:43 UTC by j-martin

We spend 2m30 out of 4 min caching the post-build. Depot should be much faster than that.

2024-11-12 21:48 UTC, alexstojda approved these changes

2024-11-12 22:14 UTC, ayahajar commented
@jm why not use 24 right away?

2024-11-12 23:41 UTC, j-martin commented
Because I copy-pasted it from somewhere else. :P

2024-11-13 14:42 UTC, silphid approved these changes

2024-11-13 16:51 UTC, ayahajar requested changes

2024-11-13 16:51 UTC, ayahajar commented on .github/workflows/build-test.yaml
> +    runs-on: depot-ubuntu-22.04-2
depot-ubuntu-24.04-2

2024-11-13 17:59 UTC, ayahajar approved these changes

2024-11-13 20:30 UTC, closed without merging

2024-11-13 20:30 UTC, j-martin commented
Closing since it would involve allowing any external PRs to run against depot.