feat/PL 2401/add filter by owners to release list
nestoca/joy pull request #85
Opened 2024-02-16 12:28 UTC by davidmdm

- **experiment(release-list): filter by project owner**

2024-02-19 15:25 UTC, alexstojda approved these changes

2024-02-21 18:57 UTC, silphid requested changes

2024-02-21 18:57 UTC, silphid commented on cmd/joy/release.go
> +	cmd.Flags().StringVarP(&owners, "owners", "o", "", "List releases by owners (comma-separated with wildcards, defaults to all)")
Don't see anything implementing wildcards, or am I missing something?

2024-02-23 14:41 UTC, silphid approved these changes

2024-02-23 16:15 UTC, merged